#!/usr/bin/env python3
"""
build_agents.py — Assembles AGENTS.md from source constraint files.

Run after editing any source file:
    python build_agents.py

The output (AGENTS.md) is what you paste into Genie Code's instructions file.
The 20,000 character limit is enforced — anything over the limit is silently
ignored by Genie Code, which causes unpredictable constraint violations.
"""

from pathlib import Path

ROOT = Path(__file__).parent

CHAR_LIMIT = 20_000
WARN_AT = int(CHAR_LIMIT * 0.85)   # warn at 85%

# Priority order matters — Genie Code reads top-to-bottom.
# Higher-priority constraints come first so they win on conflict.
SOURCES = [
    ("GLOBAL RULES",    ROOT / "GLOBAL_RULES.md"),
    ("STACK",           ROOT / "STACK.md"),
    ("ERROR HANDLING",  ROOT / "modules" / "error_handling.md"),
    ("LOGGING",         ROOT / "modules" / "logging.md"),
    ("DATA ACCESS",     ROOT / "modules" / "data_access.md"),
    ("UI PATTERNS",     ROOT / "modules" / "ui_patterns.md"),
    ("DLT PIPELINES",   ROOT / "modules" / "dlt_pipeline.md"),
    ("TESTING",         ROOT / "modules" / "testing.md"),
]

HEADER = """\
# AI Genie Factory — Constraints
<!-- Generated by build_agents.py — do not edit directly.
     Edit source files and re-run: python build_agents.py
     Load the output (AGENTS.md) into Genie Code instructions file. -->

"""


def build():
    sections = []
    missing = []

    for title, path in SOURCES:
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            print(f"  SKIP  {path.name} — file not found")
            continue

        lines = path.read_text(encoding="utf-8").splitlines()

        # Strip the redundant title line each source file starts with
        if lines and lines[0].strip().upper() == title.upper():
            lines = lines[1:]

        content = "\n".join(lines).strip()
        sections.append(f"---\n\n## {title}\n\n{content}")

    output = HEADER + "\n\n".join(sections) + "\n"
    chars = len(output)
    pct = chars / CHAR_LIMIT * 100

    # Write the file
    target = ROOT / "AGENTS.md"
    target.write_text(output, encoding="utf-8")

    # Status report
    print()
    if chars > CHAR_LIMIT:
        status = "❌  OVER LIMIT"
    elif chars > WARN_AT:
        status = "⚠️   NEAR LIMIT"
    else:
        status = "✅  OK"

    print(f"{status}  AGENTS.md — {chars:,} / {CHAR_LIMIT:,} chars ({pct:.1f}%)")

    if chars > CHAR_LIMIT:
        print()
        print("  ERROR: AGENTS.md exceeds the 20,000 character Genie Code limit.")
        print("  Content beyond that point is silently ignored — constraints WILL be violated.")
        print()
        print("  Options:")
        print("  1. Split: put high-priority rules in .assistant_workspace_instructions.md")
        print("             and app-specific modules in .assistant_instructions.md")
        print("  2. Trim:  remove less-used modules from SOURCES and add them per-prompt")
    elif chars > WARN_AT:
        print()
        print(f"  WARNING: {CHAR_LIMIT - chars:,} chars remaining before limit.")
        print("  Avoid adding large modules without trimming existing ones first.")

    if missing:
        print()
        print(f"  MISSING FILES ({len(missing)}):")
        for f in missing:
            print(f"    - {f}")
        print("  Create these files to include their constraints in AGENTS.md.")

    print()
    print("  Next step: copy AGENTS.md contents into your Genie Code instructions file.")
    print("  Location: Genie Code → gear icon → User instructions → Add instructions file")
    print("  Path: /Users/<your-email>/.assistant_instructions.md")


if __name__ == "__main__":
    build()
