#!/usr/bin/env python3
"""
build_agents.py — Assembles the lean AGENTS.md from core constraint modules only.

Skills (data-access, ui-patterns, dlt-pipeline, testing-scaffold, databricks-app-design)
live in skills/ and are loaded by Genie Code Agent mode on demand — NOT compiled here.

Run after editing GLOBAL_RULES.md, STACK.md, or modules/error_handling.md / logging.md:
    python build_agents.py

Workspace deployment:
    Copy AGENTS.md contents → Workspace/.assistant/instructions.md  (all users)
    or /Users/<email>/.assistant/instructions.md                     (you only)

Skills deployment:
    Copy each skills/<name>/ folder →
    Workspace/.assistant/skills/<name>/   (workspace-wide)
    /Users/<email>/.assistant/skills/<name>/   (personal)
"""

from pathlib import Path

ROOT = Path(__file__).parent
CHAR_LIMIT = 20_000
WARN_AT = int(CHAR_LIMIT * 0.60)  # warn at 60% — lean target

# Only always-on guardrails here.
# Domain skills (data-access, ux-design, dlt-pipeline, etc.) live in skills/ folder.
SOURCES = [
    ("GLOBAL RULES",   ROOT / "GLOBAL_RULES.md"),
    ("STACK",          ROOT / "STACK.md"),
    ("ERROR HANDLING", ROOT / "modules" / "error_handling.md"),
    ("LOGGING",        ROOT / "modules" / "logging.md"),
]

HEADER = """\
# AI Genie Factory — Core Constraints
<!-- Generated by build_agents.py — do not edit directly.
     Edit source files and re-run: python build_agents.py

     This file contains ONLY always-on guardrails (platform rules, stack, error handling, logging).
     Domain skills (UX/UI design, data access, DLT pipelines, testing) live in skills/ and are
     loaded automatically by Genie Code Agent mode when relevant, or @mentioned by name. -->

"""

def build():
    sections = []
    missing = []

    for title, path in SOURCES:
        if not path.exists():
            missing.append(str(path.relative_to(ROOT)))
            print(f"  SKIP  {path.name} — not found")
            continue
        lines = path.read_text(encoding="utf-8").splitlines()
        if lines and lines[0].strip().upper() == title.upper():
            lines = lines[1:]
        content = "\n".join(lines).strip()
        sections.append(f"---\n\n## {title}\n\n{content}")

    output = HEADER + "\n\n".join(sections) + "\n"
    chars = len(output)
    pct = chars / CHAR_LIMIT * 100

    target = ROOT / "AGENTS.md"
    target.write_text(output, encoding="utf-8")

    if chars > CHAR_LIMIT:
        status = "❌  OVER LIMIT"
    elif chars > WARN_AT:
        status = "⚠️   GETTING HEAVY — skills should not be here"
    else:
        status = "✅  LEAN"

    print(f"\n{status}  AGENTS.md — {chars:,} / {CHAR_LIMIT:,} chars ({pct:.1f}%)")
    print(f"   Target: keep under {WARN_AT:,} chars (60%) — domain knowledge belongs in skills/\n")

    if missing:
        print(f"  MISSING: {', '.join(missing)}\n")

    print("  Skills to deploy separately (copy to Workspace/.assistant/skills/):")
    skills_dir = ROOT / "skills"
    if skills_dir.exists():
        for s in sorted(skills_dir.iterdir()):
            if s.is_dir() and (s / "SKILL.md").exists():
                print(f"    @{s.name}")

if __name__ == "__main__":
    build()
