#!/usr/bin/env python3
"""Combines all constraint .md files into AGENTS.md."""

from pathlib import Path

ROOT = Path(__file__).parent

SOURCES = [
    ("GLOBAL RULES", ROOT / "GLOBAL_RULES.md"),
    ("STACK", ROOT / "STACK.md"),
    ("DATA ACCESS", ROOT / "modules" / "data_access.md"),
    ("UI PATTERNS", ROOT / "modules" / "ui_patterns.md"),
]

HEADER = """\
# AI Genie Factory — Constraints

<!-- Generated by build_agents.py — do not edit directly.
     Edit the source files and re-run: python build_agents.py -->

"""

def build():
    sections = []
    for title, path in SOURCES:
        lines = path.read_text().splitlines()
        # Strip the leading title line that each source file repeats
        if lines and lines[0].strip().upper() == title.upper():
            lines = lines[1:]
        content = "\n".join(lines).strip()
        sections.append(f"---\n\n## {title}\n\n{content}")

    output = HEADER + "\n\n".join(sections) + "\n"

    target = ROOT / "AGENTS.md"
    target.write_text(output)

    chars = len(output)
    limit = 20_000
    print(f"AGENTS.md written — {chars:,} / {limit:,} characters ({chars/limit*100:.1f}% of limit)")
    if chars > limit:
        print("WARNING: exceeds 20,000 character limit — Genie Code will ignore content past that point")

if __name__ == "__main__":
    build()
